# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Build and upload app to App Store"
  lane :deploy do
    match(
      type: "appstore",
      git_url: ENV["MATCH_GIT_URL"],
      readonly: true # Chỉ đọc khi chạy CI, không tạo mới
    )

    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )

    build_app(
      scheme: "WheelSpinApp",
      export_method: "app-store"
    )

    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end