# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Build and upload app to App Store"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["KEY_ID"],
      issuer_id: ENV["ISSUER_ID"],
      key_filepath: "./fastlane/AuthKey_45P36M8DM8.p8",
      in_house: false # optional but may be required if using match/sigh
    )
  
    match(
      type: "appstore",
      git_url: ENV["MATCH_GIT_URL"],
      readonly: true # Chỉ đọc khi chạy CI, không tạo mới
    )

    latest_build = latest_testflight_build_number(
      app_identifier: "khoadang.WheelSpinApp",
      api_key: api_key # Thêm vào nếu dùng API Key cho TestFlight
    )

    increment_build_number(
      build_number: latest_build + 1
    )

    build_app(
      scheme: "WheelSpinApp",
      export_method: "app-store",
      clean: true,
      verbose: true,
      export_options: {
      provisioningProfiles: {"khoadang.WheelSpinApp" => "match AppStore khoadang.WheelSpinApp"},
      signingStyle: "manual",
      teamID: "FQ4L47BZFJ",
      signingCertificate: "Apple Distribution: Dang Khoa (FQ4L47BZFJ)"
    }
    )

    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true,
      api_key: api_key
    )
  end
end